### PR TITLE
fix: get plugins.json from correct url

### LINKED ISSUE #113: Bug: Unable to get local plugins.json
After the monorepo migration, the location of the `plugins.json` is changed and all its references need to be updated.

### PR DESCRIPTION
**Pull request by tedraykov**
Fixes #113

Signed-off-by: tedraykov <tedraykov@gmail.com>

### CODE REVIEW

File: commands/create-project-api.js [hunk 1]
```diff
@@ -88,8 +71,7 @@ async function getFileFromCore(fileName, rootDir = reactionAppRoot) {
 function updateEnv(envData) {
   const env = parse(envData);
   env.MONGO_URL = "mongodb://localhost:27017/reaction";
-  const updatedEnv = stringify(env);
-  return updatedEnv;
+  return stringify(env);
```
Comment (zenweasel) [inline commands/create-project-api.js:74]: I really dislike this style (process and return in one) since it makes it debugging much more difficult

**Review by brent-hoover — APPROVED** [review]
